language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "spring-bees"
    token:
      secure: "5348fd459773428f29efbe3f50eb665433bb4516"

cache:
  directories:
    - "$HOME/.m2"


script: 
  - mvn clean install -B checkstyle:check 
  - mvn -B jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN
  - mvn clean verify -B sonar:sonar -Dsonar.projectKey=spring-bees_spring-bee -Dsonar.login=${SONAR_TOKEN} -DskipTests
